[footer]
  issue = "Un problème avec cette page ?"
  issue_url_content = "Corrigez-la sur Github"
  contact = "Besoin d'aide ? Contactez"
  contact_email = "eirbware[at]enseirb-matmeca.fr"
  copyright = "Eirbware"
  links_title = "Sections du site"
